### ISSUE TITLE
Bug on PHP 8+

### ISSUE THREAD

**Issue by JeffPaetkau** [concretecms/migration_tool#8]
Attempting to view an import batch throws an exception "Undefined variable $activeProcesses" on view_batch.php line 7 if PHP is version 8+. Downgrading to PHP 7.4 works around the issue.

**Comment by dangrth** [comment]
I think this is due to a change in PHP 8 where undefined variables trigger a warning instead of a notice : [incompatibility list](https://www.php.net/manual/fr/migration80.incompatible.php)

The quick and dirty workaround I used is to add a test if the variable exists first :

`
<?php if (isset($activeProcesses) && $activeProcesses) { ?>
`

**Comment by jbender0** [comment]
I found the same thing, so I created a pull request: https://github.com/concretecms/migration_tool/pull/17

**Comment by aembler** [comment]
Thanks for the fix!
